---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-extractor-api
  namespace: petrosa-apps
  labels:
    app: binance-data-extractor
    component: api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: data-extractor-api
  namespace: petrosa-apps
  labels:
    app: binance-data-extractor
    component: api
rules:
- apiGroups: ["batch"]
  resources: ["cronjobs", "jobs"]
  verbs: ["get", "list", "watch", "patch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: data-extractor-api
  namespace: petrosa-apps
  labels:
    app: binance-data-extractor
    component: api
subjects:
- kind: ServiceAccount
  name: data-extractor-api
  namespace: petrosa-apps
roleRef:
  kind: Role
  name: data-extractor-api
  apiGroup: rbac.authorization.k8s.io
